# Generated by Django 4.2.3 on 2023-07-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='close_day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_owner',
            field=models.CharField(max_length=50),
        ),
    ]
