# Generated by Django 4.2.3 on 2023-07-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_life_cycle_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
